const actionType = {
  // content loading
  CONTENT_LOADING: 'CONTENT_LOADING',

  // auth action types
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  // fetch user action types
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',

  // fetch all meetups action types
  FETCH_MEETUPS_SUCCESS: 'FETCH_MEETUPS_SUCCESS',
  FETCH_MEETUPS_ERROR: 'FETCH_MEETUPS_ERROR',

  // specific meetup action types
  SINGLE_MEETUP_SUCCESS: 'SINGLE_MEETUP_SUCCESS',
  SINGLE_MEETUP_ERROR: 'SINGLE_MEETUP_ERROR',

  // rsvp action types
  RSVP_GET_SUCCESS: 'RSVP_GET_SUCCESS',

  // rsvp post action type
  RSVP_POST_SUCCESS: 'RSVP_POST_SUCCESS',

  // post question success and error action types
  POST_QUESTION_SUCCESS: 'POST_QUESTION_SUCCESS',
  POST_QUESTION_ERROR: 'POST_QUESTION_ERROR',

  // upvote and downvote action types
  UPVOTE_DOWNVOTE_SUCCESS: 'UPVOTE_DOWNVOTE_SUCCESS',

  // post comment action types
  POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
  POST_COMMENT_ERROR: 'POST_COMMENT_ERROR',

  // Question count by users
  USER_QUESTION_COUNT_SUCCESS: 'USER_QUESTION_COUNT_SUCCESS',
  USER_QUESTION_COUNT_ERROR: 'USER_QUESTION_COUNT_ERROR',

  // comment count by users
  USER_COMMENT_COUNT_SUCCESS: 'USER_COMMENT_COUNT_SUCCESS',

  // upcoming meetups action types
  FETCH_UPCOMING_MEETUP_SUCCESS: 'FETCH_UPCOMING_MEETUP_SUCCESS',
  FETCH_UPCOMING_MEETUP_ERROR: 'FETCH_UPCOMING_MEETUP_ERROR',

  // post meetups by admin
  POST_MEETUP_SUCCESS: 'POST_MEETUP_SUCCESS',
  POST_MEETUP_ERROR: 'POST_MEETUP_ERROR',
};

export default actionType;
