const actionType = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  ALL_MEETUPS_SUCCESS: 'ALL_MEETUPS_SUCCESS',
  ALL_MEETUPS_ERROR: 'ALL_MEETUPS_ERROR',
};

export default actionType;
